# Generated by Django 5.1.15 on 2026-06-24 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], max_length=20)),
                ('duration_days', models.PositiveIntegerField(help_text='Duration in days for calculation')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='one_time', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.gymorganization')),
            ],
            options={
                'db_table': 'membership_plans',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MemberMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('freeze_start', models.DateField(blank=True, null=True)),
                ('freeze_end', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.member')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.gymorganization')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_plans', to='memberships.membershipplan')),
            ],
            options={
                'db_table': 'member_memberships',
            },
        ),
        migrations.CreateModel(
            name='MembershipRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_end_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('amount_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
                ('member_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='memberships.membermembership')),
                ('renewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership_renewals',
            },
        ),
        migrations.AddIndex(
            model_name='membermembership',
            index=models.Index(fields=['member', 'is_active'], name='member_memb_member__f88f82_idx'),
        ),
        migrations.AddIndex(
            model_name='membermembership',
            index=models.Index(fields=['end_date'], name='member_memb_end_dat_68a7d2_idx'),
        ),
    ]
