# Generated by Django 5.1.15 on 2026-07-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_gym_code_alter_member_unique_together'),
        ('memberships', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membermembership',
            index=models.Index(fields=['organization', 'member'], name='member_memb_organiz_08fc3c_idx'),
        ),
    ]
