# Generated by Django 5.1.15 on 2026-07-03 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_organization_receptionistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionistprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receptionists', to=settings.AUTH_USER_MODEL),
        ),
    ]
