# Generated by Django 5.1.15 on 2026-06-24 16:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_in_method', models.CharField(choices=[('qr', 'QR Scan'), ('manual', 'Manual Entry')], max_length=10)),
                ('session_type', models.CharField(blank=True, default='regular', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'attendance_logs',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qr_codes',
            },
        ),
    ]
