# Generated by Django 5.1.15 on 2026-06-24 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('members', '0001_initial'),
        ('organizations', '0001_initial'),
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='members.member'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.gymorganization'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='trainers.trainer'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='organizations.branch'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['member', 'check_in_time'], name='attendance__member__07757f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['branch', 'check_in_time'], name='attendance__branch__69c5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['organization', 'check_in_time'], name='attendance__organiz_a78eed_idx'),
        ),
    ]
