# Generated by Django 5.1.15 on 2026-06-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='check_in_method',
            field=models.CharField(choices=[('qr', 'QR Scan'), ('manual', 'Manual Entry'), ('code', 'Code Entry')], max_length=10),
        ),
    ]
