# Generated by Django 5.1.15 on 2026-07-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancelog_check_in_method'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['expires_at'], name='qr_codes_expires_a30ec8_idx'),
        ),
    ]
