# Generated by Django 5.1.15 on 2026-07-05 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsession',
            name='pt_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='personal_training.ptmembership'),
        ),
    ]
