# Generated by Django 5.1.15 on 2026-07-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_gym_code_alter_member_unique_together'),
        ('organizations', '0001_initial'),
        ('personal_training', '0002_alter_ptsession_pt_membership'),
        ('trainers', '0002_trainer_created_by'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ptmembership',
            index=models.Index(fields=['organization', 'member'], name='pt_membersh_organiz_1afd2a_idx'),
        ),
        migrations.AddIndex(
            model_name='ptsession',
            index=models.Index(fields=['organization', 'scheduled_date'], name='pt_sessions_organiz_a95c7f_idx'),
        ),
    ]
