# Generated by Django 5.1.15 on 2026-08-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('staff', 'Staff'), ('member', 'Member')], max_length=10)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('valid_for', models.DateField(help_text='IST calendar date this code works on')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='organizations.gymorganization')),
            ],
            options={
                'db_table': 'invite_codes',
                'constraints': [models.UniqueConstraint(fields=('organization', 'branch', 'kind', 'valid_for'), name='uniq_invite_code_per_branch_kind_day')],
            },
        ),
    ]
