# Generated by Django 5.1.15 on 2026-08-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymorganization',
            name='banner_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gymorganization',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gymorganization',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gymorganization',
            name='picture_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
