# Generated by Django 5.1.15 on 2026-06-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gym_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
