# Generated by Django 5.1.15 on 2026-07-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_whatsapp_number'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gym_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('organization', 'gym_code')},
        ),
    ]
