# Generated by Django 5.1.15 on 2026-08-01 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_gym_code_alter_member_unique_together'),
        ('organizations', '0001_initial'),
        ('payments', '0002_payment_gateway_payment_gateway_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date the payment is due. Used by the payment-due reminder job.', null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'due_date'], name='payments_status_422e56_idx'),
        ),
    ]
