# Generated by Django 5.1.15 on 2026-06-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_caches',
            },
        ),
    ]
