# Generated by Django 5.1.15 on 2026-06-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcache',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_caches', to='organizations.gymorganization'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardcache',
            unique_together={('organization', 'cache_key')},
        ),
    ]
