# Generated by Django 5.1.15 on 2026-06-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event', models.CharField(choices=[('membership_expiry', 'Membership Expiry Reminder'), ('payment_due', 'Payment Due Reminder'), ('pt_session_reminder', 'PT Session Reminder'), ('announcement', 'Gym Announcement'), ('staff_invite', 'Staff Invite'), ('welcome', 'Welcome Email')], max_length=50, unique=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_logs',
                'indexes': [models.Index(fields=['status'], name='email_logs_status_e3be55_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('membership_expiry', 'Membership Expiry Reminder'), ('payment_due', 'Payment Due Reminder'), ('pt_session_reminder', 'PT Session Reminder'), ('announcement', 'Gym Announcement'), ('staff_invite', 'Staff Invite'), ('welcome', 'Welcome Email')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('reminder_days', models.IntegerField(blank=True, help_text='Days before event to send reminder', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='organizations.gymorganization')),
            ],
            options={
                'db_table': 'notification_preferences',
                'unique_together': {('organization', 'event')},
            },
        ),
    ]
