# Generated by Django 5.1.15 on 2026-07-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_whatsapp_log_preferences'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='whatsappmessagelog',
            new_name='whatsapp_me_status_4262b3_idx',
            old_name='whatsapp_message_logs_status_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessagelog',
            new_name='whatsapp_me_organiz_418621_idx',
            old_name='whatsapp_msg_log_org_created_idx',
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event',
            field=models.CharField(choices=[('membership_expiry', 'Membership Expiry Reminder'), ('membership_expired', 'Membership Expired'), ('payment_due', 'Payment Due Reminder'), ('pt_session_reminder', 'PT Session Reminder'), ('announcement', 'Gym Announcement'), ('staff_invite', 'Staff Invite'), ('welcome', 'Welcome')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event',
            field=models.CharField(choices=[('membership_expiry', 'Membership Expiry Reminder'), ('membership_expired', 'Membership Expired'), ('payment_due', 'Payment Due Reminder'), ('pt_session_reminder', 'PT Session Reminder'), ('announcement', 'Gym Announcement'), ('staff_invite', 'Staff Invite'), ('welcome', 'Welcome')], max_length=50),
        ),
    ]
